// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqN2mb2coDZONu0a_vKZbuWeR2dsDBZ_k',
    appId: '1:73612795158:web:536940f63bd1c5d3f5c437',
    messagingSenderId: '73612795158',
    projectId: 'pushnotification-7db5f',
    authDomain: 'pushnotification-7db5f.firebaseapp.com',
    storageBucket: 'pushnotification-7db5f.appspot.com',
    measurementId: 'G-8X22VJQHST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZW1RzS7GnqVnlori4dxA0Db4afMxSCNg',
    appId: '1:73612795158:android:9479a27aefa81177f5c437',
    messagingSenderId: '73612795158',
    projectId: 'pushnotification-7db5f',
    storageBucket: 'pushnotification-7db5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy7AXAhK1EzIyRUvt1JaMfNeUGrQwA4-Q',
    appId: '1:73612795158:ios:15d1cb92b345b17ef5c437',
    messagingSenderId: '73612795158',
    projectId: 'pushnotification-7db5f',
    storageBucket: 'pushnotification-7db5f.appspot.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy7AXAhK1EzIyRUvt1JaMfNeUGrQwA4-Q',
    appId: '1:73612795158:ios:15d1cb92b345b17ef5c437',
    messagingSenderId: '73612795158',
    projectId: 'pushnotification-7db5f',
    storageBucket: 'pushnotification-7db5f.appspot.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqN2mb2coDZONu0a_vKZbuWeR2dsDBZ_k',
    appId: '1:73612795158:web:b19b8848f18813fef5c437',
    messagingSenderId: '73612795158',
    projectId: 'pushnotification-7db5f',
    authDomain: 'pushnotification-7db5f.firebaseapp.com',
    storageBucket: 'pushnotification-7db5f.appspot.com',
    measurementId: 'G-B1FKJLVS7Q',
  );
}
